"""Prometheus metrics for the agent and the skill bank.

Every metric lives in a CollectorRegistry passed in by whoever serves it, so two engines in one
process, or two tests, never share counts. Counters are exported with a _total suffix.
"""

from __future__ import annotations

from collections.abc import Callable

from prometheus_client import (
    CollectorRegistry,
    Counter,
    Gauge,
    Histogram,
    start_http_server,
)

from engine.core.types.agent import TraceEvent, TraceKind

SECONDS = (0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0, 600.0)


def new_registry() -> CollectorRegistry:
    """An empty registry."""
    return CollectorRegistry()


def serve_metrics(
    registry: CollectorRegistry, host: str, port: int
) -> tuple[int, Callable[[], None]]:
    """Serve the registry at /metrics on host:port from a daemon thread; port 0 takes a free one.

    Returns the bound port and a call that stops the server. Raises OSError when the port is taken.
    """
    server, thread = start_http_server(port, addr=host, registry=registry)

    def stop() -> None:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)

    return server.server_port, stop


def stats(registry: CollectorRegistry) -> dict[str, float]:
    """Every sample in the registry, flattened to name{label=value,...} -> number.

    Counters are totals since the process started, and each histogram carries its _sum and
    _count; whoever shows them decides what a rate or a mean is.
    """
    out: dict[str, float] = {}
    for metric in registry.collect():
        for sample in metric.samples:
            labels = ",".join(f"{k}={v}" for k, v in sorted(sample.labels.items()))
            out[f"{sample.name}{{{labels}}}" if labels else sample.name] = sample.value
    return out


def skills_label(skills: list[str]) -> str:
    """One label value for a set of skills: none, or the names sorted and joined by a plus."""
    return "+".join(sorted(skills)) or "none"


class AgentMetrics:
    """What the agent does: runs, steps, model calls, tokens, tools, policy, skill picks."""

    def __init__(self, registry: CollectorRegistry) -> None:
        self.runs = Counter(
            "bijou_agent_runs", "Runs that ended, by status.", ["status"], registry=registry
        )
        self.run_seconds = Histogram(
            "bijou_agent_run_seconds", "Wall time of a run.", buckets=SECONDS, registry=registry
        )
        self.steps = Counter(
            "bijou_agent_steps", "Steps that ended, by status.", ["status"], registry=registry
        )
        self.model_calls = Counter(
            "bijou_agent_model_calls",
            "Chat model calls, by purpose and outcome.",
            ["purpose", "outcome"],
            registry=registry,
        )
        self.model_call_seconds = Histogram(
            "bijou_agent_model_call_seconds",
            "Chat model call latency, by purpose.",
            ["purpose"],
            buckets=SECONDS,
            registry=registry,
        )
        self.tokens = Counter(
            "bijou_agent_tokens", "Chat model tokens, by kind.", ["kind"], registry=registry
        )
        self.tool_calls = Counter(
            "bijou_agent_tool_calls",
            "Tool calls, by tool and whether they succeeded.",
            ["tool", "ok"],
            registry=registry,
        )
        self.tool_seconds = Histogram(
            "bijou_agent_tool_seconds",
            "Tool call latency, by tool.",
            ["tool"],
            buckets=SECONDS,
            registry=registry,
        )
        self.policy = Counter(
            "bijou_agent_policy_decisions",
            "Policy decisions on tool calls.",
            ["decision"],
            registry=registry,
        )
        self.skill_picks = Counter(
            "bijou_agent_skill_picks",
            "Skills the selector equipped for a step.",
            ["skills"],
            registry=registry,
        )


class BankMetrics:
    """What the skill bank does: generations, their latency, lock waits, what it loaded."""

    def __init__(self, registry: CollectorRegistry) -> None:
        self.generations = Counter(
            "bijou_bank_generations",
            "Generations, by equipped skills and outcome.",
            ["skills", "outcome"],
            registry=registry,
        )
        self.generation_seconds = Histogram(
            "bijou_bank_generation_seconds",
            "Generation latency, by equipped skills, lock wait excluded.",
            ["skills"],
            buckets=SECONDS,
            registry=registry,
        )
        self.lock_wait_seconds = Histogram(
            "bijou_bank_lock_wait_seconds",
            "Time a generation waited for the model.",
            buckets=SECONDS,
            registry=registry,
        )
        self.tokens = Counter(
            "bijou_bank_tokens", "Positions generated by the diffusion model.", registry=registry
        )
        self.trained_skills = Gauge(
            "bijou_bank_trained_skills", "Trained skills the bank loaded.", registry=registry
        )
        self.load_seconds = Gauge(
            "bijou_bank_load_seconds", "Time the bank took to load.", registry=registry
        )


class MetricsSink:
    """Counts trace events into AgentMetrics. Satisfies TraceSink."""

    def __init__(self, metrics: AgentMetrics) -> None:
        self.metrics = metrics

    def emit(self, event: TraceEvent) -> None:
        try:
            self._count(event)
        except (KeyError, TypeError, ValueError):
            return

    def _count(self, event: TraceEvent) -> None:
        m, data = self.metrics, event.data
        if event.kind is TraceKind.RUN_DONE:
            m.runs.labels(str(data["status"])).inc()
            if "duration_ms" in data:
                m.run_seconds.observe(float(data["duration_ms"]) / 1000)
        elif event.kind is TraceKind.STEP_DONE:
            m.steps.labels(str(data["status"])).inc()
        elif event.kind is TraceKind.MODEL_CALL:
            purpose = str(data["purpose"])
            m.model_calls.labels(purpose, "ok").inc()
            m.model_call_seconds.labels(purpose).observe(float(data["duration_ms"]) / 1000)
            m.tokens.labels("prompt").inc(int(data["prompt_tokens"]))
            m.tokens.labels("completion").inc(int(data["completion_tokens"]))
        elif event.kind is TraceKind.MODEL_ERROR:
            m.model_calls.labels(str(data["purpose"]), "error").inc()
        elif event.kind is TraceKind.TOOL_RESULT:
            tool = str(data["tool"])
            m.tool_calls.labels(tool, "true" if data["ok"] else "false").inc()
            m.tool_seconds.labels(tool).observe(float(data["duration_ms"]) / 1000)
        elif event.kind is TraceKind.POLICY:
            m.policy.labels(str(data["decision"])).inc()
        elif event.kind is TraceKind.SKILLS_PICKED:
            m.skill_picks.labels(skills_label(list(data["skills"]))).inc()
